# Generated by Django 4.1.3 on 2022-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('contact_type', models.IntegerField(choices=[[0, 'Pedido de Información'], [1, 'Queja por Producto'], [2, 'Felicitaciones']], verbose_name='Tipo de Contacto')),
                ('subscription', models.BooleanField(default=False, verbose_name='Suscribirme a Correos Informativos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
        ),
    ]
